#define USB_SUSPEND_WAKEUP_DELAY 0
#define NO_AUTO_SHIFT_TAB
#define NO_AUTO_SHIFT_ALPHA
#define SERIAL_NUMBER "9QzP7/pjDd9D"
#define LAYER_STATE_8BIT
#define RGB_MATRIX_STARTUP_SPD 60
#define LEADER_NO_TIMEOUT
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250
