name: Build Firmware
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build firmware with Nix
        run: nix build
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonlander-firmware-${{ github.sha }}
          path: result/bin/moonlander-default.bin
          if-no-files-found: error
