name: Sync Oryx Layout
on:
  workflow_dispatch:
env:
  LAYOUT_ID: "9QzP7"
  LAYOUT_GEOMETRY: "moonlander"
permissions:
  contents: write
jobs:
  sync-oryx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout oryx branch
        uses: actions/checkout@v4
        with:
          ref: oryx
          fetch-depth: 0
      - name: Download latest Oryx layout
        id: download
        run: |
          response=$(curl --location 'https://oryx.zsa.io/graphql' \
            --header 'Content-Type: application/json' \
            --data '{"query":"query getLayout($hashId: String!, $revisionId: String!, $geometry: String) {layout(hashId: $hashId, geometry: $geometry, revisionId: $revisionId) {  revision { hashId, qmkVersion, title }}}","variables":{"hashId":"${{ env.LAYOUT_ID }}","geometry":"${{ env.LAYOUT_GEOMETRY }}","revisionId":"latest"}}' \
            | jq '.data.layout.revision | [.hashId, .qmkVersion, .title]')

          hash_id=$(echo "${response}" | jq -r '.[0]')
          change_description=$(echo "${response}" | jq -r '.[2]')
          if [[ -z "${change_description}" ]]; then
            change_description="latest layout modification made with Oryx"
          fi

          curl -L "https://oryx.zsa.io/source/${hash_id}" -o source.zip
          echo "change_description=${change_description}" >> "$GITHUB_OUTPUT"
      - name: Update oryx branch with new layout
        env:
          CHANGE_DESCRIPTION: ${{ steps.download.outputs.change_description }}
        run: |
          rm -rf src/*
          mkdir -p src
          unzip -oj source.zip '*_source/*' -d src/
          rm source.zip

          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add src/
          printf "oryx: %s\n" "$CHANGE_DESCRIPTION" | git commit -F - || echo "No layout change"
          git push
      - name: Merge Oryx into master (DON'T push yet)
        run: |
          git fetch origin master
          git checkout master
          git merge -Xours oryx -m "Merge Oryx layout update"
          # NB: DON'T push yet, make sure the build actually passes before pushing to master
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build merged firmware (validation)
        run: nix build
        # If this fails, the workflow stops and master isn't pushed
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonlander-merged-${{ github.sha }}
          path: result/bin/moonlander-default.bin
      - name: Push to master (only if build succeeded)
        run: git push
